### ISSUE TITLE
Error when using module w/o jQuery

### ISSUE THREAD

**Issue by rhewitt22** [joeybaker/visible-element#1]
I used the code directly from the readme:

```
var visibleElement = require('visible-element'),
      visible = visibleElement();

visible.inViewport(document.getElementById('map'));
```

Gives the following error on line 15: 
`Uncaught TypeError: Expecting a function in instanceof check, but got undefined`

Commenting out that line seems to solve the issue.

```
// special bonus for those using jQuery
// if (el instanceof $) el = el[0]
```

**Comment by joeybaker** [comment]
Thanks @rhewitt22! Fixed and released as 1.0.1
